---
- name: Discover NVMe EBS
  disk_config:
    config: "{{ disk_additional_disks }}"
  become: true
  register: __disk_config

- name: Set fact if ansible version is 2.5 or older
  block:
  - set_fact:
      disk_additional_disks: "{{ __disk_config['ansible_facts']['config'] }}"
    when:
      - __disk_config is defined and __disk_config | success and 'ansible_facts' in __disk_config
  when:
    - ansible_version.full is version('2.5.0', '<')

- name: Set fact if ansible version is newer than 2.5
  block:
  - set_fact:
      disk_additional_disks: "{{ __disk_config['ansible_facts']['config'] }}"
    when:
      - __disk_config is defined and __disk_config is not successful and 'ansible_facts' in __disk_config
  when:
    - ansible_version.full is version('2.5.0', '>=')
